app_admin_help_question:
    resource: |
        alias: app.help_question
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: index
        grid: app_admin_help_question
        vars:
            all:
                header: Help
                subheader: Manage your question
            index:
                icon: 'file image outline'
    type: sylius.resource