sylius_admin_taxon:
  resource: |
    alias: sylius.taxon
    path: category
    section: admin
    templates: SyliusAdminBundle:Taxon
    except: ['show', 'index']
    redirect: update
    permission: true
    vars:
        all:
            subheader: sylius.ui.manage_categorization_of_your_products
            templates:
                form: "@SyliusAdmin/Taxon/_form.html.twig"
  type: sylius.resource

sylius_admin_taxon_index:
  path: /category/
  methods: [GET]
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: sylius_admin_taxon_create
    permanent: true

sylius_admin_taxon_create_for_parent:
  path: /category/new/{id}
  methods: [GET, POST]
  defaults:
    _controller: sylius.controller.taxon:createAction
    _sylius:
      section: admin
      permission: true
      template: 'SyliusAdminBundle:Taxon:create.html.twig'
      redirect: sylius_admin_taxon_update
      factory:
        method: createForParent
        arguments: ['expr:notFoundOnNull(service("sylius.repository.taxon").find($id))']
      vars:
        subheader: sylius.ui.manage_categorization_of_your_products
        templates:
          form: "@SyliusAdmin/Taxon/_form.html.twig"

app_admin_taxon_pre_create:
  path: /category/pre-create/{type}
  methods: [GET, POST]
  defaults:
    _controller: sylius.controller.taxon:preCreateAction

sylius_admin_ajax_taxon_swap:
  path: /{taxonSource}/{taxonDestination}/swap
  methods: [POST,PUT]
  defaults:
    _controller: sylius.controller.taxon:swapPositionAction
    _format: json
#    _sylius:
#      permission: true
#      form: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonPositionType