AppBundle\Entity\BlogProducts:
    type: entity
    repositoryClass: AppBundle\Repository\BlogProductsRepository
    table: app_blog_products
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        product:
            targetEntity: AppBundle\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL