AppBundle\Entity\BlogPostImage:
    type: entity
    table: app_blog_post_image
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        aspectRatio:
            column: aspect_ratio
            type: string
            nullable: true
        type:
            type: string
            nullable: true
        path:
            type: string
            nullable: true
    manyToOne:
        blogPost:
            targetEntity: AppBundle\Entity\BlogPost
            inversedBy: blogPostImage
            joinColumn:
                name: blog_post_id
                referencedColumnName: id