AppBundle\Entity\BuyersGuideProductRelated:
    type: entity
    table: app_buyers_guide_product_related
    repositoryClass: AppBundle\Repository\BuyersGuideProductRelatedRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        currentProduct:
            targetEntity: AppBundle\Entity\Product
        relatedProduct:
            targetEntity: AppBundle\Entity\Product