AppBundle\Entity\Contact:
    type: entity
    table: app_contact
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        contactPosition:
            type: string
            column: contact_position
            nullable: true
    manyToOne:
        contactMainTitle:
            targetEntity: AppBundle\Entity\ContactTitle
            inversedBy: contact
            joinColumn:
                name: contact_main_title_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
    oneToMany:
        contactContent:
            targetEntity: AppBundle\Entity\ContactContent
            mappedBy: contact
            cascade: [ persist , remove ]


