AppBundle\Entity\DealerImage:
    type: entity
    table: app_dealer_image
    manyToOne:
        owner:
            targetEntity: AppBundle\Entity\Dealer
            inversedBy: images
            joinColumn:
                name: owner_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE