AppBundle\Entity\DropDownOption:
  type: entity
  table: app_drop_down_option
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    price:
      type: integer
      nullable: true
    position:
      type: integer
      nullable: true
      options:
        default: 0

  manyToOne:
    dropDown:
      targetEntity: AppBundle\Entity\DropDown
      inversedBy: dropDownOptions
      fetch: EXTRA_LAZY

  manyToMany:
    orderItems:
      targetEntity: AppBundle\Entity\OrderItem
      inversedBy: dropDownOptions
      fetch: EXTRA_LAZY
      orphanRemoval: true

  oneToMany:
    orderItemDropDownOptions:
      targetEntity: AppBundle\Entity\OrderItemDropDownOption
      mappedBy: dropDownOption
      fetch: EXTRA_LAZY
      orphanRemoval: true
      onDelete: CASCADE
      cascade: [remove, persist]
