AppBundle\Entity\HelpPage:
  type: entity
  table: app_help_page
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
    metaTitle:
      type: string
    metaDescription:
      type: string
    metaKeywords:
      type: text

