AppBundle\Entity\ProductPropertyImage:
    type: entity
    table: product_property_image
    manyToOne:
        owner:
            targetEntity: AppBundle\Entity\ProductProperty
            inversedBy: images
            joinColumn:
                name: owner_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE