AppBundle\Entity\ProductDescriptionImage:
    type: entity
    table: app_product_description_image
    manyToOne:
        owner:
            targetEntity: AppBundle\Entity\ProductDescription
            inversedBy: images
            joinColumn:
                name: owner_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE