AppBundle\Entity\SlideImage:
    type: entity
    table: slide_image
    manyToOne:
        owner:
            targetEntity: AppBundle\Entity\Slide
            inversedBy: images
            joinColumn:
                name: owner_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE