sylius_grid:
  grids:
    app_admin_drop_down:
      driver:
        name: doctrine/orm
        options:
          class: AppBundle\Entity\DropDown
      sorting:
        name: asc
      fields:
        code:
          type: string
          label: Code
          sortable: ~
        name:
          type: string
          label: Name
          sortable: ~
      filters:
        code:
          type: string
          label: sylius.ui.code
        name:
          type: string
          label: sylius.ui.name
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
