sylius_grid:
    grids:
        app_admin_general_option:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\GeneralOption
            fields:

                key:
                   type: string
                   label: Key
                name:
                    type: string
                    label: Name
                value:
                    type: string
                    label: Value
                enable:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
