sylius_grid:
    grids:
        app_admin_slider:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Slider
            fields:
                code:
                    type: string
                    label: Code
                name:
                    type: string
                    label: Name
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"

            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
