sylius_grid:
    grids:
        app_admin_user_logistic:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\UserLogistic
            fields:
                first_name:
                    type: string
                    label: First name
                last_name:
                    type: string
                    label: Last name
                email:
                    type: string
                    label: Email
                created_at:
                    type: datetime
                    label: Created at
                warehouse:
                    type: string
                    label: Warehouse
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete